name: Use Secrets
on:
  push:
    paths:
      - ".github/workflows/use-secrets.yml"

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: "Step: Dump secrets context content"
        run: echo '${{ toJSON(secrets) }}'|jq
        shell: bash
      - uses: actions/checkout@v2
      - name: "Step: Grade use-secrets activity"
        id: check-secrets
        uses: ./.github/actions/check-secrets-action
        with:
          secrets-context: ${{ toJSON(secrets) }}
          your-secret: ${{ secrets.EXERCISE_PAT }}
